apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: k8s-webhook-validate
  labels:
    app: k8s-webhook-validate
webhooks:
  - name: k8s-webhook-validate.codepy.net
    sideEffects: None
    admissionReviewVersions: ["v1", "v1beta1"]
    clientConfig:
      service:
        name: k8s-webhook
        namespace: kube-system
        path: "/validate"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeE1EZ3lNREEyTkRNd05Gb1hEVE14TURneE9EQTJORE13TkZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBT3hZCnBnckhmTnVHd2NINmhLNVBPYlR6dWtQallMR3BiS1dXc3B5WEtLaVR2NEc3SnVEUnRGZHorcXNzYmZieStHRm0KM0djUFg3WUlyVnUvZ1R4NU1ZSUZia2p1V2hCOGdtdmx6WFBtZVUyMEVGLzlZTG01SnZnM0JiRmlCY3hpd0JiWQo5WFpWQTB5MjdpYnFPZjVNUWtDZWhlWVRqanNPU3lCd3BZQ1VlTDZlMjdiVVUveStBYVFBMXp0V0dIRm1VaFJVClpQN0pJVGpRcHJDRmgzVERUdE9EOHpZWkFJaWRIVEVZbXgwVkh2cDlrSkpObHVHMTR2SUVReUJCUndhSDZRaE8KNGNOdEJITFNxcGZSU2ZCVzlCRXFwNmQ3V2Q3YVRXK2M0Ny9TdUhaUjZIR0hpSlNMSkx5SWYyYUU3VkNKSk9nbwpXTlpITm04bTFrS2JXWDJteHUwQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFJZGFpQlV3ZExOck10V2NpLzN4bWN3KytHMSsKS2Y5dlpJOXo2V01pOUN3K0VrRkRXNkIzR212NjRNTm5TQ09kZHY4Y2o0VFNBRGVDVlUrK1VqcDJLRTF6cVFwUApQMTFZTkJvUzlFTlRGSTc5Lzc0R3hLR21VSmd1UlVOeEkzMVB1S0xCczhMY09yRjl1UkNxK0hXWDNIVmd1VlBXCnZKOXZTdlhzL0ticmszQktvTmEzWXgwVW9kRmhPdnEralBVQncyMlQ3RzhHd1dlOWM2Z1RlYThrRU5iTHlqT3UKRDRMZVdyTWZHM1ROYUlxUzE4VTFMbkw3TXZUbDMyby9XbG9zaXdTMzJEeUt4OW1EZS9qMDBCczZoUjR6QUx6YwpwN2tMWVgzWW9INENuZmVqdEtUdkxCSEFXL2ZaZjJUK0VXSTdZWnJUL2lFaXkxSm9JcEgzTnUvbC9tUT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    rules:
      - operations: [ "CREATE" ]
        apiGroups: ["apps", ""]
        apiVersions: ["v1"]
        resources: ["deployments"]
    namespaceSelector:
      matchLabels:
        k8s-webhook: enabled
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: k8s-webhook-mutate
  labels:
    app: k8s-webhook-mutate
webhooks:
  - name: k8s-webhook-mutate.codepy.net
    sideEffects: None
    admissionReviewVersions: ["v1", "v1beta1"]
    clientConfig:
      service:
        name: k8s-webhook
        namespace: kube-system
        path: "/mutate"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeE1EZ3lNREEyTkRNd05Gb1hEVE14TURneE9EQTJORE13TkZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBT3hZCnBnckhmTnVHd2NINmhLNVBPYlR6dWtQallMR3BiS1dXc3B5WEtLaVR2NEc3SnVEUnRGZHorcXNzYmZieStHRm0KM0djUFg3WUlyVnUvZ1R4NU1ZSUZia2p1V2hCOGdtdmx6WFBtZVUyMEVGLzlZTG01SnZnM0JiRmlCY3hpd0JiWQo5WFpWQTB5MjdpYnFPZjVNUWtDZWhlWVRqanNPU3lCd3BZQ1VlTDZlMjdiVVUveStBYVFBMXp0V0dIRm1VaFJVClpQN0pJVGpRcHJDRmgzVERUdE9EOHpZWkFJaWRIVEVZbXgwVkh2cDlrSkpObHVHMTR2SUVReUJCUndhSDZRaE8KNGNOdEJITFNxcGZSU2ZCVzlCRXFwNmQ3V2Q3YVRXK2M0Ny9TdUhaUjZIR0hpSlNMSkx5SWYyYUU3VkNKSk9nbwpXTlpITm04bTFrS2JXWDJteHUwQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFJZGFpQlV3ZExOck10V2NpLzN4bWN3KytHMSsKS2Y5dlpJOXo2V01pOUN3K0VrRkRXNkIzR212NjRNTm5TQ09kZHY4Y2o0VFNBRGVDVlUrK1VqcDJLRTF6cVFwUApQMTFZTkJvUzlFTlRGSTc5Lzc0R3hLR21VSmd1UlVOeEkzMVB1S0xCczhMY09yRjl1UkNxK0hXWDNIVmd1VlBXCnZKOXZTdlhzL0ticmszQktvTmEzWXgwVW9kRmhPdnEralBVQncyMlQ3RzhHd1dlOWM2Z1RlYThrRU5iTHlqT3UKRDRMZVdyTWZHM1ROYUlxUzE4VTFMbkw3TXZUbDMyby9XbG9zaXdTMzJEeUt4OW1EZS9qMDBCczZoUjR6QUx6YwpwN2tMWVgzWW9INENuZmVqdEtUdkxCSEFXL2ZaZjJUK0VXSTdZWnJUL2lFaXkxSm9JcEgzTnUvbC9tUT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    rules:
      - operations: [ "CREATE" ]
        apiGroups: ["apps", ""]
        apiVersions: ["v1"]
        resources: ["deployments", "service"]
    namespaceSelector:
      matchLabels:
        k8s-webhook: enabled