apiVersion: v1
kind: Service
metadata:
  labels:
    app: k8s-webhook
  name: k8s-webhook
  namespace: kube-system
spec:
  type: ClusterIP
  ports:
    - port: 443
      protocol: TCP
      targetPort: 8080
  selector:
    app: k8s-webhook
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-webhook
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-webhook
  template:
    metadata:
      labels:
        app: k8s-webhook
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: k8s-webhook
              topologyKey: kubernetes.io/hostname
      containers:
        - name: k8s-webhook
          resources:
            requests:
              cpu: 100m
              memory: 500Mi
            limits:
              cpu: 100m
              memory: 500Mi
          image: lanceyuan/k8s-webhook:v0.0.6
          imagePullPolicy: IfNotPresent
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 10
            httpGet:
              path: /health
              scheme: HTTPS
              port: 8080
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 10
            httpGet:
              path: /health
              scheme: HTTPS
              port: 8080
          ports:
            - name: http
              protocol: TCP
              containerPort: 8080
          volumeMounts:
            - name: cert
              mountPath: /opt/cert
      volumes:
        - name: cert
          secret:
            secretName: k8s-cert